[versions]
openrndr = "0.4.1"
orx = "0.4.1"

[libraries]
openrndr-color = { group = "org.openrndr", name = "openrndr-color", version.ref = "openrndr" }
openrndr-math = { group = "org.openrndr", name = "openrndr-math", version.ref = "openrndr" }
orx-color = { group = "org.openrndr.extra", name = "orx-color", version.ref = "orx" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "1.7.10" }
intellij = { id = "org.jetbrains.intellij", version = "1.8.0" }
changelog = { id = "org.jetbrains.changelog", version = "1.3.1" }