name: Build
on:
  # Trigger the workflow on pushes to only the 'main' branch (this avoids duplicate checks being run e.g. for dependabot pull requests)
  push:
    branches: [ main ]
  # Trigger the workflow on any pull request
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./main

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          path: main

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      # TODO: Fetch version number for regex from gradle properties
      - name: Find latest tag for given IntelliJ version
        uses: oprypin/find-latest-tag@v1.1.0
        id: intellij-tag
        with:
          repository: JetBrains/intellij-community
          regex: ^idea/222.*

      - name: Checkout intellij-community repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          repository: JetBrains/intellij-community
          ref: ${{ steps.intellij-tag.outputs.tag }}
          path: intellij-community

      - name: Setup Java environment for the next steps
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: gradle

      - name: Run tests
        run: |
          chmod +x ./gradlew
          ./gradlew test

      - name: Collect test results of failed tests
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: tests-result
          path: ${{ github.workspace }}/build/reports/tests